version: '3'
services:
  webapp:
    build:
      context: ./
    image: tsfran/orbis-training-docker/1.0.0
    volumes:
      - '$PWD:/app'
    working_dir: /app
    ports: 
     - '1042:3030'
     - '35729:35729'
    command: npm start 