version: '3'
services:
  webapp:
    image: tsfran/orbis-training-docker:1.0.0
    volumes:
      - $PWD:/app
    working_dir: /app
    ports: 
      - 1042:3030
      - 35729:35729
    command: npm start

  test:
    image: node:10.10.0-slim
    command: curl http://webapp:3030/